version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: chatmate-frontend-dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=development

  frontend-prod:
    build: .
    ports:
      - "5173:5173"  
    container_name: chatmate-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production